{% set name = "napari-mri" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-mri-{{ version }}.tar.gz
  sha256: 03fee9bb319a660e81451a21f3cbc13fe2a03e255e79b6a93015812cf138986b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - pytest-runner >=5.2
    - python {{ python_min }}
    - setuptools-scm
  run:
    - napari-plugin-engine >=0.1.4
    - nibabel
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - napari_mri
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-mri/
  summary: A simple plugin to use with napari for 3D-viewing of                  Magnetic Resonance Imaging file formats
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
